### ISSUE TITLE
Support for Cassandra running on Kubernetes

### ISSUE THREAD

**Issue by tetsushiawano** [newrelic/nri-cassandra#40]
Hello.
I am running Cassandra as a Kubernetes statefulset.
Does this library also support Cassandra running on Kubernetes statefulset?

**Comment by davidbrota** [comment]
Hello,

Please, check the official documentation ([link](https://docs.newrelic.com/docs/integrations/kubernetes-integration/link-apps-services/monitor-services-running-kubernetes/)) where we describe how to monitor services, like Cassandra, on Kubernetes.

We would also like to encourage you to discuss this topic in the [Explorers Hub](https://discuss.newrelic.com/c/full-stack-observability/infrastructure/107).
