### ISSUE TITLE
Add additional Cassandra V2 metrics

### ISSUE THREAD

**Issue by adiosspandit** [newrelic/nri-cassandra#81]
## Cassandra V2 metrics
A customer would like to add support to pull some new metrics from Cassandra V2

## Feature Description
Cassandra V2 has some more JMX metrics that are of interetest and critical. It will be great if we can add support for these metrics
Attaching missing metrics requested : [Cassandra2_MissingMetrics.xlsx](https://github.com/newrelic/nri-cassandra/files/7989383/Cassandra2_MissingMetrics.xlsx)
 

## Additional context
Customer is using Cassandra V2 which is not officially supported by nri-cassandra but it still works and fetches the JMX metrics. Customer has migrated from another solution which provided additional JMX metrics. Many customer teams depend on those metrics for dashboards and alerting. 

## Priority
Please help us better understand this feature request by choosing a priority from the following options:  Really Want

Thank you!

**Comment by gsanchezgavier** [comment]
Hi @adiosspandit  , could you submit this FR on AHA?  that is where we track internal FR. cc @mangulonr
